### ISSUE TITLE
"Error: Cannot find module" running yarn start using @neutrinojs/node

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1125]
Running `yarn start` with a create-project created `@neutrinojs/node` project (using `master`), I get:

```
test-project $ yarn start
yarn run v1.10.0
$ webpack-dev-server --mode development
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\Users\Ed\src\test-project\build\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
i ｢wdm｣: Hash: 17e1b7606a72c809f718
Version: webpack 4.17.1
Time: 935ms
Built at: 09/20/2018 6:17:11 PM
   Asset     Size  Chunks             Chunk Names
index.js  122 KiB   index  [emitted]  index
Entrypoint index = index.js
[../neutrino/node_modules/webpack/hot/log-apply-result.js] 1.27 KiB {index} [built]
[../neutrino/node_modules/webpack/hot/log.js] 1.11 KiB {index} [built]
[../neutrino/node_modules/webpack/hot/poll.js?1000] 1.15 KiB {index} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.78 KiB {index} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {index} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {index} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {index} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {index} [built]
[./src/app.js] 111 bytes {index} [built]
[./src/index.js] 275 bytes {index} [built]
[http] external "http" 42 bytes {index} [built]
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./src/index ../neutrino/node_modules/webpack/hot/poll.js?1000 52 bytes {index} [built]
[loglevel] external "loglevel" 42 bytes {index} [built]
[strip-ansi] external "strip-ansi" 42 bytes {index} [built]
[url] external "url" 42 bytes {index} [built]
    + 5 hidden modules
i ｢wdm｣: Compiled successfully.
```

**Comment by edmorley** [comment]
Eugh I forgot to update the `start` script to use webpack not webpack-dev-server (using a shared test project).
