### ISSUE TITLE
neutrino --inspect throws an error

### ISSUE THREAD

**Issue by helfi92** [neutrinojs/neutrino#1167]
### Bug
- What version of Neutrino are you using?
`v9`
- Are you using the Yarn client or the npm client? What version?
yarn, `v1.10.1`
- What version of Node.js are you using?
`v8.10`
- What operating system are you using?
macOS High Sierra
- What did you do?
Attempt to migrate to neutrino v9
- What did you expect to happen?
`neutrino --inspect --mode development` to work.
- What actually happened, contrary to your expectations?
`neutrino --inspect --mode development` throws the following error:

```bash
➜  taskcluster-web git:(neutrino-v9) ✗ neutrino --inspect --mode development
/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/webpack-chain/src/Plugin.js:11
      this.init((Plugin, args = []) => new Plugin(...args));
                                       ^

TypeError: Plugin is not a constructor
    at init (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/webpack-chain/src/Plugin.js:11:40)
    at Object.toConfig (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/webpack-chain/src/Plugin.js:42:22)
    at clean.Object.assign.plugins.plugins.values.map.plugin (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/webpack-chain/src/Config.js:125:61)
    at Array.map (<anonymous>)
    at module.exports.toConfig (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/webpack-chain/src/Config.js:125:40)
    at module.exports.toString (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/webpack-chain/src/Config.js:137:41)
    at Object.output (/Users/haali/Documents/Mozilla/projects/neutrino-dev/packages/neutrino/index.js:27:37)
    at Object.<anonymous> (/Users/haali/Documents/Mozilla/projects/neutrino-dev/packages/neutrino/bin/neutrino.js:9:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by edmorley** [comment]
I believe this is because of a stale globally linked copy of development neutrino:
https://github.com/taskcluster/taskcluster-web/pull/157#discussion_r224497370

**Comment by edmorley** [comment]
Closing since this was due to a an out of date globally linked copy of Neutrino:
https://github.com/taskcluster/taskcluster-web/pull/157#discussion_r224548609
