### ISSUE TITLE
[v9] Cannot find module 'neutrino/errors'

### ISSUE THREAD

**Issue by ringods** [neutrinojs/neutrino#1298]
### Bug or issue?

Please try to answer the following questions:

- What version of Neutrino are you using? 9.0.0-rc.0
- Are you trying to use any presets? If so, which ones, and what versions? no
- Are you using the Yarn client or the npm client? What version? npm 6.7.0
- What version of Node.js are you using? v11.8.0
- What operating system are you using? MacOS Mojave v10.14.2
- What did you do? Creating a custom preset, using `@neutrinojs/style-loader@next`
- What did you expect to happen? Expected not to have an error on an internal module not being found.
- What actually happened, contrary to your expectations? See following stacktrace:

```
$ npm start

> zoho-sites-elate-theme@0.0.1 start /Users/ringods/Projects/personal/zoho-sites-elate-template
> webpack --mode=development


An error occurred when loading the Neutrino configuration.

{ Error: Cannot find module 'neutrino/errors'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:611:15)
    at Function.Module._load (internal/modules/cjs/loader.js:537:25)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/ringods/Projects/personal/neutrino-preset-zoho-sites-template/node_modules/@neutrinojs/style-loader/index.js:2:32)
    at Module._compile (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/ringods/Projects/personal/neutrino-preset-zoho-sites-template/index.js:1:83)
    at Module._compile (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at requireFromRoot (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/neutrino/Neutrino.js:34:10)
    at Neutrino.use (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/neutrino/Neutrino.js:216:16)
    at middleware.use.map.usage (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/neutrino/Neutrino.js:236:44)
    at Array.map (<anonymous>)
    at Neutrino.use (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/neutrino/Neutrino.js:236:26)
    at Neutrino.use (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/neutrino/Neutrino.js:216:12)
    at middleware.use.map.usage (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/neutrino/Neutrino.js:236:44)
    at Array.map (<anonymous>)
    at Neutrino.use (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/neutrino/Neutrino.js:236:26)
    at module.exports (/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules/neutrino/index.js:36:16) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zoho-sites-elate-theme@0.0.1 start: `webpack --mode=development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zoho-sites-elate-theme@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ringods/.npm/_logs/2019-02-07T20_53_21_037Z-debug.log
```

Setup:
* the preset: https://gitlab.com/ringods/neutrino-preset-zoho-sites-template
* the project using the preset: https://gitlab.com/ringods/zoho-sites-elate-template  (branch `neutrino`)
Note that the project has the preset as a dependency via a relative local folder. To run this, first clone both projects side-by-side, then run `npm ci` in `zoho-sites-elate-template` followed by `npm start` to reproduce the error.

**Comment by edmorley** [comment]
Hi! `@neutrinojs/style-loader` has a peer dependency on `neutrino`, so it's expected that an error will occur if it's missing. NPM will generate a warning in this case when installing.

**Comment by ringods** [comment]
@edmorley the project using the preset has this as `devDependencies`:

```
  "devDependencies": {
    "neutrino": "^9.0.0-rc.0",
    "neutrino-preset-zoho-sites-template": "file:../neutrino-preset-zoho-sites-template",
    "webpack": "^4.8.3",
    "webpack-cli": "^3.2.3"
  }
```

So Neutrino 9 is installed. I can browse the files of it under `node_modules`.

**Comment by ringods** [comment]
Found the problem, and it is not a Neutrino problem: https://stackoverflow.com/a/53215430/7269988

My development setup was done via `npm install ../neutrino-preset-zoho-sites-template`, but this doesn't seem to work correctly with peer dependencies.

After setting the `NODE_PATH` correctly, all modules seem to resolve correctly:

```
export NODE_PATH=/Users/ringods/Projects/personal/zoho-sites-elate-template/node_modules:/Users/ringods/Projects/personal/neutrino-preset-zoho-sites-template/node_modules
```

Docs: [`NODE_PATH`](https://nodejs.org/docs/latest-v8.x/api/all.html#cli_node_path_path)
