### ISSUE TITLE
Karma cant run tests as it expects Buffer Node api to be present

### ISSUE THREAD

**Issue by colmbrady** [neutrinojs/neutrino#1363]
### Bug or issue?

BUG

Please try to answer the following questions:

- What version of Neutrino are you using?

9.0.0-0

- Are you trying to use any presets? If so, which ones, and what versions?

"neutrino": "^9.0.0-0",
"@neutrinojs/karma": "^9.0.0-0",
"@neutrinojs/library": "^9.0.0-0",

- Are you using the Yarn client or the npm client? What version?

YARN

- What version of Node.js are you using?
v11.2.0

- What operating system are you using?

Mac

- What did you do?

Attempting to run Karma tests

- What did you expect to happen?

Karma runs my tests.

- What actually happened, contrary to your expectations?

Received error:

```
15 04 2019 16:26:29.869:INFO [karma-server]: Karma v4.0.1 server started at http://0.0.0.0:9876/
15 04 2019 16:26:29.872:INFO [launcher]: Launching browsers ChromeHeadless, Chrome with concurrency unlimited
15 04 2019 16:26:29.876:INFO [launcher]: Starting browser ChromeHeadless
15 04 2019 16:26:30.009:INFO [launcher]: Starting browser Chrome
15 04 2019 16:26:30.844:INFO [HeadlessChrome 73.0.3683 (Mac OS X 10.13.6)]: Connected on socket vi9wjukA-uIKQqGWAAAA with id 95778862
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR
  {
    "message": "Uncaught ReferenceError: Buffer is not defined\nat test/containers/ErrorBoundaryContainer_test.js:14790:20\n\nReferenceError: Buffer is not defined\n    at Object.../../node_modules/core-util-is/lib/util.js (test/containers/ErrorBoundaryContainer_test.js:14790:20)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.<anonymous> (test/containers/ErrorBoundaryContainer_test.js:92172:12)\n    at Object.../../node_modules/readable-stream/lib/_stream_readable.js (test/containers/ErrorBoundaryContainer_test.js:93125:30)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/readable-stream/readable-browser.js (test/containers/ErrorBoundaryContainer_test.js:94259:28)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/stream-browserify/index.js (test/containers/ErrorBoundaryContainer_test.js:104532:19)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/parse5/lib/parser/parser_stream.js (test/containers/ErrorBoundaryContainer_test.js:56890:22)",
    "str": "Uncaught ReferenceError: Buffer is not defined\nat test/containers/ErrorBoundaryContainer_test.js:14790:20\n\nReferenceError: Buffer is not defined\n    at Object.../../node_modules/core-util-is/lib/util.js (test/containers/ErrorBoundaryContainer_test.js:14790:20)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.<anonymous> (test/containers/ErrorBoundaryContainer_test.js:92172:12)\n    at Object.../../node_modules/readable-stream/lib/_stream_readable.js (test/containers/ErrorBoundaryContainer_test.js:93125:30)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/readable-stream/readable-browser.js (test/containers/ErrorBoundaryContainer_test.js:94259:28)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/stream-browserify/index.js (test/containers/ErrorBoundaryContainer_test.js:104532:19)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/parse5/lib/parser/parser_stream.js (test/containers/ErrorBoundaryContainer_test.js:56890:22)"
  }
15 04 2019 16:26:31.432:INFO [Chrome 73.0.3683 (Mac OS X 10.13.6)]: Connected on socket WwY3WanT9Mx4qWsYAAAB with id 42314150
Chrome 73.0.3683 (Mac OS X 10.13.6) ERROR
  {
    "message": "Uncaught ReferenceError: Buffer is not defined\nat test/containers/ErrorBoundaryContainer_test.js:14790:20\n\nReferenceError: Buffer is not defined\n    at Object.../../node_modules/core-util-is/lib/util.js (test/containers/ErrorBoundaryContainer_test.js:14790:20)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.<anonymous> (test/containers/ErrorBoundaryContainer_test.js:92172:12)\n    at Object.../../node_modules/readable-stream/lib/_stream_readable.js (test/containers/ErrorBoundaryContainer_test.js:93125:30)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/readable-stream/readable-browser.js (test/containers/ErrorBoundaryContainer_test.js:94259:28)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/stream-browserify/index.js (test/containers/ErrorBoundaryContainer_test.js:104532:19)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/parse5/lib/parser/parser_stream.js (test/containers/ErrorBoundaryContainer_test.js:56890:22)",
    "str": "Uncaught ReferenceError: Buffer is not defined\nat test/containers/ErrorBoundaryContainer_test.js:14790:20\n\nReferenceError: Buffer is not defined\n    at Object.../../node_modules/core-util-is/lib/util.js (test/containers/ErrorBoundaryContainer_test.js:14790:20)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.<anonymous> (test/containers/ErrorBoundaryContainer_test.js:92172:12)\n    at Object.../../node_modules/readable-stream/lib/_stream_readable.js (test/containers/ErrorBoundaryContainer_test.js:93125:30)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/readable-stream/readable-browser.js (test/containers/ErrorBoundaryContainer_test.js:94259:28)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/stream-browserify/index.js (test/containers/ErrorBoundaryContainer_test.js:104532:19)\n    at __webpack_require__ (test/containers/ErrorBoundaryContainer_test.js:30:30)\n    at Object.../../node_modules/parse5/lib/parser/parser_stream.js (test/containers/ErrorBoundaryContainer_test.js:56890:22)"
  }

Finished in 0.84 secs / 0 secs @ 16:26:31 GMT+1200 (New Zealand Standard Time)

SUMMARY:
✔ 0 tests completed
```

From what I can tell:

1. There is code in `@neutrino/library preset` which mocks Node objects when building a web module. https://github.com/neutrinojs/neutrino/blob/master/packages/library/index.js#L114
2. However, for Karma tests, you actually want these Node objects to be present as the Karma/Mocha runner I guess uses those APIs..
3. Perhaps that code should NOT mock the node APIs if ```options.target === 'web' && process.env.NODE_ENV !== true```

**Comment by colmbrady** [comment]
Unfortunately I could not reproduce this issue with the minimal repo I created for #1360.

Note, that when I changed: https://github.com/neutrinojs/neutrino/blob/master/packages/library/index.js#L114
to be ```options.target === 'web' && process.env.NODE_ENV !== true```, Karma can run my tests.

**Comment by edmorley** [comment]
Hi! In the past a project I was working on encountered the same issue (even with older Neutrino versions). I never quite tracked down what package was requiring the use of Buffer. 

In general I think Neutrino disabling the polyfilling of potentially bloated/unwanted Node-only features is the right thing to do. It's worth noting that webpack 5 (in alpha) disables most polyfilling by default now.

If you could create a reduced testcase it would help work out whether we should change this default and/or document the need to override it when using certain packages.

In the meantime, I would use the webpack-chain API to enable Buffer polyfiling in your project (https://master.neutrinojs.org/webpack-chain/#config-node).

**Comment by colmbrady** [comment]
Im closing as I cant reproduce this with the RC1 build. Also, I think my neutrino config was not valid in the test project for #1360.
