### ISSUE TITLE
core-js version detection does not work with ranges

### ISSUE THREAD

**Issue by davidje13** [neutrinojs/neutrino#1370]
Dependencies are often written as `^x.y.z` to request the latest minor/patch release of a dependency. However this is incompatible with the new `core-js` detection code:

```
An error occurred when loading the Neutrino configuration.

TypeError: Invalid Version: ^3.0.1
    at new SemVer (.../node_modules/@neutrinojs/web/node_modules/semver/semver.js:323:11)
    at Function.major (.../node_modules/@neutrinojs/web/node_modules/semver/semver.js:599:10)
    at neutrino (.../node_modules/@neutrinojs/web/index.js:137:22)
    at Neutrino.use (.../node_modules/neutrino/Neutrino.js:171:26)
    at neutrino (.../node_modules/@neutrinojs/react/index.js:56:12)
    at Neutrino.use (.../node_modules/neutrino/Neutrino.js:171:26)
    at use.forEach.use (.../node_modules/neutrino/index.js:49:37)
    at Array.forEach (<anonymous>)
    at module.exports (.../node_modules/neutrino/index.js:49:13)
    at Object.<anonymous> (.../.eslintrc.js:3:18)
```

The following formats should be accepted for full compatibility:

- `2` / `3` (currently rejected)
- `2.x` / `3.x` (currently rejected)
- `2.0.x` / `3.0.x` (currently rejected)
- `2.0.0` / `3.0.0` (currently accepted)
- `~2.0.0` / `~3.0.0` (currently rejected)
- `^2.0.0` / `^3.0.0` (currently rejected)

See https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept for details

---

- What version of Neutrino are you using? 9.0.0-rc.1
- Are you trying to use any presets? If so, which ones, and what versions? react (also affects node & others)
- Are you using the Yarn client or the npm client? What version? npm 6.5.0
- What version of Node.js are you using? 11.6.0
- What operating system are you using? OSX

Related:
- https://github.com/neutrinojs/neutrino/issues/1337
- https://github.com/neutrinojs/neutrino/pull/1341

**Comment by amorriscode** [comment]
I'm having the same issue. Commenting so I can follow along.
